# default
author: Hojeong.Kwak
email: hojeong3709.kwak@lge.com  

markdown: kramdown
title: Hojeong.Kwak's Blog
tagline: Software Developer@LGE
locale: "ko"
enconding: utf-8

# Required Packages ( Gems )
gems:
  - jekyll-sitemap
  - jekyll-feed

# Reference
reference:
    github-pages: "https://pages.github.com"
    github-hojeong3709-repository: "https://github.com/hojeong3709"
    jekyll-plugins-supported-by-github-pages: "https://help.github.com/en/articles/adding-jekyll-plugins-to-a-github-pages-site"

# Navigation
navigation:
    home: "/"
    about: "/about"
    sitemap: "/sitemap.xml"
    feed: "/feed.xml"
           
# Category
category: ["Project", "DevOps with Docker/KS8", "Machine Learning", "Deep Learning", "Reinforcement Learning", "Software Engineering"]
